Bot:
Memes:
  approach:
    image: "cogs/meme/Approaching.png"
    user1_box: [600, 800, 850, 1050]
    user1_align: "center-center"
    user2_box: [400, 10, 650, 260]
    user2_align: "center-center"
  beautiful:
    image: "cogs/meme/Beautiful.png"
    user1_box: [60, 840, 280, 1060]
    user1_align: "center-center"
    user2_box: [480, 855, 700, 1075]
    user2_align: "center-center"
    user3_box: [0, 300, 650, 800]
    user3_align: "lower-left"
  trump:
    image: "cogs/meme/Trump.png"
    user1_box: [390, 1000, 570, 1200]
    user1_align: "center-center"
    user2_box: [0, 0, 959, 959]
    user2_align: "lower-center"