Bot:
Memes:
  approach:
    image: "cogs/meme/Approaching.png"
    user1: !!python/tuple [600, 800]
    user1_resize: !!python/tuple [250, 250]
    user2: !!python/tuple [400, 10]
    user2_resize: !!python/tuple [250, 250]
  beautiful:
    image: "cogs/meme/Beautiful.png"
    user1: !!python/tuple [60, 840]
    user1_resize: !!python/tuple [220, 220]
    user2: !!python/tuple [480, 855]
    user2_resize: !!python/tuple [220, 220]
    user3: !!python/tuple [150, 300]
    user3_resize: !!python/tuple [500, 500]